name: pix2pixV2
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python=3.8
- pytorch=1.11.0
- scipy=1.8.0
- pip
- pip:
  - dominate==2.6.0
  - torchvision==0.12.0
  - Pillow==9.1.0
  - numpy==1.22.3
  - visdom==0.1.8.9
